clinc_system/clinc_system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("doctor.urls"), name='doctor'),
    path('', include("patient.urls"), name='patient'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

clinc_system/doctor/urls.py
import imp
from django.urls import path
from doctor import views


app_name = 'doctor'

urlpatterns = [

    path('get_medcine/', view=views.get_medcine, name='get_medcine'),




]

clinc_system/patient/urls.py
import imp
from django.urls import path
from django.contrib.auth import views
from patient.views import register,login,index,logOut,appointment


app_name = 'patient'

urlpatterns = [
    path('', view=index, name='index'),
    path('register', view=register, name='register'),
    path('login', view=login, name='login'),
    path('logOut', view=logOut, name='logOut'),
    path('appointment', view=appointment, name='appointment'),


]

clinc_system/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <meta http-equiv="X-UA-Compatible" content="ie=edge">

  <link type="text/css" rel="stylesheet" href="{% static "css/slick.css" %}"/>


  <meta name="copyright" content="MACode ID, https://macodeid.com/">

  <title>One Health - Medical Center HTML5 Template</title>

  <link rel="stylesheet" href="  {% static "css/maicons.css" %}">

  <link rel="stylesheet" href="  {% static "css/bootstrap.css" %}">


  <link rel="stylesheet" href="  {% static "vendor/owl-carousel/css/owl.carousel.css" %}">


  <link rel="stylesheet" href="  {% static "vendor/animate/animate.css" %}">

  <link rel="stylesheet" href="  {% static "css/theme.css" %}">

</head>

<body>
  <!-- Back to top button -->

    <div class="back-to-top"></div>
    <header>
        <div class="topbar">
          <div class="container">
            <div class="row">
              <div class="col-sm-8 text-sm">
                <div class="site-info">
                  <a href="#">{{ user.first_name }} {{ user.last_name }}</a>
                  <span class="divider">|</span>
                  <a href="mailto: {{ user.email }}"><span class="mai-mail text-primary"></span>  {{ user.email }}</a>
                </div>
              </div>
              <div class="col-sm-4 text-right text-sm">
                <div class="social-mini-button">
                  <a href="#"><span class="mai-logo-facebook-f"></span></a>
                  <a href="#"><span class="mai-logo-twitter"></span></a>
                  <a href="#"><span class="mai-logo-dribbble"></span></a>
                  <a href="#"><span class="mai-logo-instagram"></span></a>
                </div>
              </div>
            </div> <!-- .row -->
          </div> <!-- .container -->
        </div> <!-- .topbar -->
    
        <nav class="navbar navbar-expand-lg navbar-light shadow-sm">
          <div class="container">
    
    
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupport" aria-controls="navbarSupport" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
    
            <div class="collapse navbar-collapse" id="navbarSupport">
              <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                  {% comment %} <a class="nav-link" href="index.html">Home</a>
                </li> {% endcomment %}
                {% comment %} <li class="nav-item">
                  <a class="nav-link" href="about.html">About Us</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="doctors.html">Doctors</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="blog.html">News</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="contact.html">Contact</a>
                </li> {% endcomment %}
                {% if user.is_authenticated %}

                <li class="nav-item">
                  <a class="btn btn-primary ml-lg-3" href="{% url 'patient:logOut' %}">LogOut</a>
                </li>                
                {% else %}

                
                <li class="nav-item">
                  <a class="btn btn-primary ml-lg-3" href="{% url 'patient:login' %}">Login / Register</a>
                </li>

                {% endif %}
              </ul>
            </div> <!-- .navbar-collapse -->
          </div> <!-- .container -->
        </nav>
      </header>


      {% block content %}{% endblock content %}



      <footer class="page-footer">
        <div class="container">
          <div class="row px-md-3">
            <div class="col-sm-6 col-lg-3 py-3">
              <h5>Company</h5>
              <ul class="footer-menu">
                <li><a href="#">About Us</a></li>
                <li><a href="#">Career</a></li>
                <li><a href="#">Editorial Team</a></li>
                <li><a href="#">Protection</a></li>
              </ul>
            </div>
            <div class="col-sm-6 col-lg-3 py-3">
              <h5>More</h5>
              <ul class="footer-menu">
                <li><a href="#">Terms & Condition</a></li>
                <li><a href="#">Privacy</a></li>
                <li><a href="#">Advertise</a></li>
                <li><a href="#">Join as Doctors</a></li>
              </ul>
            </div>
            <div class="col-sm-6 col-lg-3 py-3">
              <h5>Our partner</h5>
              <ul class="footer-menu">
                <li><a href="#">One-Fitness</a></li>
                <li><a href="#">One-Drugs</a></li>
                <li><a href="#">One-Live</a></li>
              </ul>
            </div>
            <div class="col-sm-6 col-lg-3 py-3">
              <h5>Contact</h5>
              <p class="footer-link mt-2">351 Willow Street Franklin, MA 02038</p>
              <a href="#" class="footer-link">701-573-7582</a>
              <a href="#" class="footer-link">healthcare@temporary.net</a>
    
              <h5 class="mt-3">Social Media</h5>
              <div class="footer-sosmed mt-3">
                <a href="#" target="_blank"><span class="mai-logo-facebook-f"></span></a>
                <a href="#" target="_blank"><span class="mai-logo-twitter"></span></a>
                <a href="#" target="_blank"><span class="mai-logo-google-plus-g"></span></a>
                <a href="#" target="_blank"><span class="mai-logo-instagram"></span></a>
                <a href="#" target="_blank"><span class="mai-logo-linkedin"></span></a>
              </div>
            </div>
          </div>
    
          <hr>
    
          <p id="copyright">Copyright &copy; 2020 <a href="https://macodeid.com/" target="_blank">MACode ID</a>. All right reserved</p>
        </div>
      </footer>
    
    <script src="static/js/jquery-3.5.1.min.js"></script>
    
    <script src="static/js/bootstrap.bundle.min.js"></script>
    
    <script src="static/vendor/owl-carousel/js/owl.carousel.min.js"></script>
    
    <script src="static/vendor/wow/wow.min.js"></script>
    
    <script src="static/js/theme.js"></script>